### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by lindatmuller** [blokadaorg/issues#4]
Would like to be able to view the list of blocked ads and, if possible, which app provided them. 

This will provide a great service for users to find out which apps are slowing down our devices and/or extreme pushing of ads. Then we can decide whether the app is worth keeping. Thanks. I appreciate your efforts in developing Blokada.

**Comment by blokadaorg** [comment]
This is a great suggestion @lindatmuller. I have added this idea to the ideas list, please vote it up. Ideas will be implemented based on their popularity.

https://feedback.userreport.com/3ff9476e-fcde-4126-a718-6187ac075da7/#idea/143596
